network: :litecoin
listen: ["0.0.0.0", 9333]
connect_peers: []
peer_addresses_path: "data/peer_addresses.yml"
max_outgoing_peers: 32
max_incoming_peers: 32
log_path: "log/development.log"
poll_limit: 10000
epoll_user: ~
